# Generated by Django 5.1.4 on 2025-02-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('access_no', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('publication_date', models.IntegerField()),
                ('edition_no', models.CharField(max_length=20, null=True)),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
            ],
        ),
    ]
